-- Rider mode: anonymous riders, the rides they report, and the raw points
-- behind each ride. Ids are UUID v4 strings in TEXT columns (generated by the
-- application) rather than UUID columns, to keep the sqlc/pgx mapping simple.
CREATE TABLE riders (
  id TEXT PRIMARY KEY CHECK (id <> ''),
  installation_id TEXT NOT NULL UNIQUE CHECK (installation_id <> ''),
  platform TEXT NOT NULL DEFAULT '',
  app_id TEXT NOT NULL DEFAULT '',
  app_version TEXT NOT NULL DEFAULT '',
  attested BOOLEAN NOT NULL DEFAULT false,
  score INTEGER NOT NULL DEFAULT 0,
  tier TEXT NOT NULL DEFAULT 'new' CHECK (tier IN ('new','trusted','blocked')),
  rides_total INTEGER NOT NULL DEFAULT 0,
  rides_corroborated INTEGER NOT NULL DEFAULT 0,
  rides_rejected INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE rides (
  id TEXT PRIMARY KEY CHECK (id <> ''),
  rider_id TEXT NOT NULL REFERENCES riders(id) ON DELETE CASCADE,
  trip_id TEXT NOT NULL,
  start_date TEXT NOT NULL,
  route_id TEXT NOT NULL DEFAULT '',
  vehicle_id TEXT NOT NULL DEFAULT '',
  boarding_stop_id TEXT NOT NULL DEFAULT '',
  destination_stop_id TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','ended')),
  state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','verified','rejected')),
  corroborated BOOLEAN NOT NULL DEFAULT false,
  end_reason TEXT NOT NULL DEFAULT '',
  points_total INTEGER NOT NULL DEFAULT 0,
  points_matched INTEGER NOT NULL DEFAULT 0,
  points_corroborated INTEGER NOT NULL DEFAULT 0,
  points_contradicted INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_rides_rider_status ON rides(rider_id, status);
CREATE INDEX idx_rides_trip ON rides(trip_id, start_date);
CREATE INDEX idx_rides_started ON rides(started_at DESC);

CREATE TABLE ride_points (
  id BIGSERIAL PRIMARY KEY,
  ride_id TEXT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  accuracy DOUBLE PRECISION,
  speed DOUBLE PRECISION,
  bearing DOUBLE PRECISION,
  timestamp BIGINT NOT NULL CHECK (timestamp > 0),
  outcome TEXT NOT NULL,
  corroboration TEXT NOT NULL,
  along_shape DOUBLE PRECISION,
  distance_to_shape DOUBLE PRECISION,
  schedule_deviation_seconds INTEGER,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ride_points_ride_ts ON ride_points(ride_id, timestamp DESC);
CREATE INDEX idx_ride_points_received ON ride_points(received_at);
