// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertRidePoint = `-- name: InsertRidePoint :batchexec
INSERT INTO ride_points (ride_id, latitude, longitude, accuracy, speed, bearing, timestamp, outcome, corroboration,
  along_shape, distance_to_shape, schedule_deviation_seconds)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
WHERE EXISTS (SELECT 1 FROM rides WHERE id = $1 AND status = 'active')
`

type InsertRidePointBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertRidePointParams struct {
	RideID                   string
	Latitude                 float64
	Longitude                float64
	Accuracy                 pgtype.Float8
	Speed                    pgtype.Float8
	Bearing                  pgtype.Float8
	Timestamp                int64
	Outcome                  string
	Corroboration            string
	AlongShape               pgtype.Float8
	DistanceToShape          pgtype.Float8
	ScheduleDeviationSeconds pgtype.Int4
}

// Points are appended in one pgx batch per request. The EXISTS guard keeps a
// late batch from appending points to a ride that has already ended, matching
// the "status = 'active'" guard on UpdateRideProgress.
func (q *Queries) InsertRidePoint(ctx context.Context, arg []InsertRidePointParams) *InsertRidePointBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RideID,
			a.Latitude,
			a.Longitude,
			a.Accuracy,
			a.Speed,
			a.Bearing,
			a.Timestamp,
			a.Outcome,
			a.Corroboration,
			a.AlongShape,
			a.DistanceToShape,
			a.ScheduleDeviationSeconds,
		}
		batch.Queue(insertRidePoint, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertRidePointBatchResults{br, len(arg), false}
}

func (b *InsertRidePointBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertRidePointBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
