// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LocationPoint struct {
	ID         int64
	VehicleID  string
	TripID     string
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	ReceivedAt pgtype.Timestamptz
	DriverID   string
}

type Ride struct {
	ID                 string
	RiderID            string
	TripID             string
	StartDate          string
	RouteID            string
	VehicleID          string
	BoardingStopID     string
	DestinationStopID  string
	Status             string
	State              string
	Corroborated       bool
	EndReason          string
	PointsTotal        int32
	PointsMatched      int32
	PointsCorroborated int32
	PointsContradicted int32
	StartedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type RidePoint struct {
	ID                       int64
	RideID                   string
	Latitude                 float64
	Longitude                float64
	Accuracy                 pgtype.Float8
	Speed                    pgtype.Float8
	Bearing                  pgtype.Float8
	Timestamp                int64
	Outcome                  string
	Corroboration            string
	AlongShape               pgtype.Float8
	DistanceToShape          pgtype.Float8
	ScheduleDeviationSeconds pgtype.Int4
	ReceivedAt               pgtype.Timestamptz
}

type Rider struct {
	ID                string
	InstallationID    string
	Platform          string
	AppID             string
	AppVersion        string
	Attested          bool
	Score             int32
	Tier              string
	RidesTotal        int32
	RidesCorroborated int32
	RidesRejected     int32
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
}

type Trip struct {
	ID         int64
	UserID     int64
	VehicleID  string
	RouteID    string
	GtfsTripID string
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Active       bool
}

type UserVehicle struct {
	UserID    int64
	VehicleID string
	CreatedAt pgtype.Timestamptz
}

type Vehicle struct {
	ID        string
	Label     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AgencyTag string
	Active    bool
}
