// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyRideOutcome = `-- name: ApplyRideOutcome :one
UPDATE riders SET
  score = LEAST(10, GREATEST(-10, score + $2)),
  rides_total = rides_total + 1,
  rides_corroborated = rides_corroborated + $3,
  rides_rejected = rides_rejected + $4,
  last_seen_at = NOW()
WHERE id = $1
RETURNING id, installation_id, platform, app_id, app_version, attested, score, tier, rides_total, rides_corroborated, rides_rejected, created_at, last_seen_at
`

type ApplyRideOutcomeParams struct {
	ID                string
	Score             int32
	RidesCorroborated int32
	RidesRejected     int32
}

func (q *Queries) ApplyRideOutcome(ctx context.Context, arg ApplyRideOutcomeParams) (Rider, error) {
	row := q.db.QueryRow(ctx, applyRideOutcome,
		arg.ID,
		arg.Score,
		arg.RidesCorroborated,
		arg.RidesRejected,
	)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Platform,
		&i.AppID,
		&i.AppVersion,
		&i.Attested,
		&i.Score,
		&i.Tier,
		&i.RidesTotal,
		&i.RidesCorroborated,
		&i.RidesRejected,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const assignUserVehicle = `-- name: AssignUserVehicle :one
INSERT INTO user_vehicles (user_id, vehicle_id)
VALUES ($1, $2)
RETURNING user_id, vehicle_id, created_at
`

type AssignUserVehicleParams struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) AssignUserVehicle(ctx context.Context, arg AssignUserVehicleParams) (UserVehicle, error) {
	row := q.db.QueryRow(ctx, assignUserVehicle, arg.UserID, arg.VehicleID)
	var i UserVehicle
	err := row.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt)
	return i, err
}

const checkUserVehicleAssignment = `-- name: CheckUserVehicleAssignment :one
SELECT user_id, vehicle_id
FROM user_vehicles
WHERE user_id = $1 AND vehicle_id = $2
`

type CheckUserVehicleAssignmentParams struct {
	UserID    int64
	VehicleID string
}

type CheckUserVehicleAssignmentRow struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) CheckUserVehicleAssignment(ctx context.Context, arg CheckUserVehicleAssignmentParams) (CheckUserVehicleAssignmentRow, error) {
	row := q.db.QueryRow(ctx, checkUserVehicleAssignment, arg.UserID, arg.VehicleID)
	var i CheckUserVehicleAssignmentRow
	err := row.Scan(&i.UserID, &i.VehicleID)
	return i, err
}

const countActiveTrips = `-- name: CountActiveTrips :one
SELECT COUNT(*) FROM trips WHERE status = 'active'
`

func (q *Queries) CountActiveTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsersByRole = `-- name: CountActiveUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1 AND active = true
`

func (q *Queries) CountActiveUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveVehicles = `-- name: CountActiveVehicles :one
SELECT COUNT(*) FROM vehicles WHERE active = true
`

func (q *Queries) CountActiveVehicles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVehicles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRidePointsForRide = `-- name: CountRidePointsForRide :one
SELECT COUNT(*) FROM ride_points WHERE ride_id = $1
`

func (q *Queries) CountRidePointsForRide(ctx context.Context, rideID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRidePointsForRide, rideID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRidersByTier = `-- name: CountRidersByTier :many
SELECT tier, COUNT(*) AS count FROM riders GROUP BY tier
`

type CountRidersByTierRow struct {
	Tier  string
	Count int64
}

func (q *Queries) CountRidersByTier(ctx context.Context) ([]CountRidersByTierRow, error) {
	rows, err := q.db.Query(ctx, countRidersByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRidersByTierRow
	for rows.Next() {
		var i CountRidersByTierRow
		if err := rows.Scan(&i.Tier, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, role, active, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

type CreateUserRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :execrows
INSERT INTO vehicles (id, label, agency_tag)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type CreateVehicleParams struct {
	ID        string
	Label     string
	AgencyTag string
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVehicle, arg.ID, arg.Label, arg.AgencyTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRidePointsBefore = `-- name: DeleteRidePointsBefore :execrows
DELETE FROM ride_points WHERE received_at < $1
`

func (q *Queries) DeleteRidePointsBefore(ctx context.Context, receivedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRidePointsBefore, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endAllActiveRides = `-- name: EndAllActiveRides :execrows
UPDATE rides SET status = 'ended', ended_at = NOW(), end_reason = $1, updated_at = NOW() WHERE status = 'active'
`

func (q *Queries) EndAllActiveRides(ctx context.Context, endReason string) (int64, error) {
	result, err := q.db.Exec(ctx, endAllActiveRides, endReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endRide = `-- name: EndRide :execrows
UPDATE rides SET status = 'ended', ended_at = NOW(), end_reason = $2, state = $3, corroborated = $4,
  points_total = $5, points_matched = $6, points_corroborated = $7, points_contradicted = $8, updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

type EndRideParams struct {
	ID                 string
	EndReason          string
	State              string
	Corroborated       bool
	PointsTotal        int32
	PointsMatched      int32
	PointsCorroborated int32
	PointsContradicted int32
}

func (q *Queries) EndRide(ctx context.Context, arg EndRideParams) (int64, error) {
	result, err := q.db.Exec(ctx, endRide,
		arg.ID,
		arg.EndReason,
		arg.State,
		arg.Corroborated,
		arg.PointsTotal,
		arg.PointsMatched,
		arg.PointsCorroborated,
		arg.PointsContradicted,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endTrip = `-- name: EndTrip :execrows
UPDATE trips
SET status = 'completed', end_time = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type EndTripParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) EndTrip(ctx context.Context, arg EndTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, endTrip, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveTripByUser = `-- name: GetActiveTripByUser :one
SELECT id, user_id, vehicle_id, route_id, gtfs_trip_id, start_time, end_time, status, created_at, updated_at
FROM trips
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveTripByUser(ctx context.Context, userID int64) (Trip, error) {
	row := q.db.QueryRow(ctx, getActiveTripByUser, userID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationHistory = `-- name: GetLocationHistory :many
SELECT latitude, longitude, bearing, speed, accuracy, timestamp, trip_id, received_at
FROM location_points
WHERE vehicle_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp DESC
LIMIT $4
`

type GetLocationHistoryParams struct {
	VehicleID   string
	Timestamp   int64
	Timestamp_2 int64
	Limit       int32
}

type GetLocationHistoryRow struct {
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	TripID     string
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) GetLocationHistory(ctx context.Context, arg GetLocationHistoryParams) ([]GetLocationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getLocationHistory,
		arg.VehicleID,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationHistoryRow
	for rows.Next() {
		var i GetLocationHistoryRow
		if err := rows.Scan(
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.TripID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLocations = `-- name: GetRecentLocations :many
SELECT DISTINCT ON (vehicle_id)
    vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id
FROM location_points
WHERE received_at > $1
ORDER BY vehicle_id, received_at DESC
`

type GetRecentLocationsRow struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) GetRecentLocations(ctx context.Context, receivedAt pgtype.Timestamptz) ([]GetRecentLocationsRow, error) {
	rows, err := q.db.Query(ctx, getRecentLocations, receivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLocationsRow
	for rows.Next() {
		var i GetRecentLocationsRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.TripID,
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRide = `-- name: GetRide :one
SELECT id, rider_id, trip_id, start_date, route_id, vehicle_id, boarding_stop_id, destination_stop_id, status, state, corroborated, end_reason, points_total, points_matched, points_corroborated, points_contradicted, started_at, ended_at, updated_at FROM rides WHERE id = $1
`

func (q *Queries) GetRide(ctx context.Context, id string) (Ride, error) {
	row := q.db.QueryRow(ctx, getRide, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.TripID,
		&i.StartDate,
		&i.RouteID,
		&i.VehicleID,
		&i.BoardingStopID,
		&i.DestinationStopID,
		&i.Status,
		&i.State,
		&i.Corroborated,
		&i.EndReason,
		&i.PointsTotal,
		&i.PointsMatched,
		&i.PointsCorroborated,
		&i.PointsContradicted,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRider = `-- name: GetRider :one
SELECT id, installation_id, platform, app_id, app_version, attested, score, tier, rides_total, rides_corroborated, rides_rejected, created_at, last_seen_at FROM riders WHERE id = $1
`

func (q *Queries) GetRider(ctx context.Context, id string) (Rider, error) {
	row := q.db.QueryRow(ctx, getRider, id)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Platform,
		&i.AppID,
		&i.AppVersion,
		&i.Attested,
		&i.Score,
		&i.Tier,
		&i.RidesTotal,
		&i.RidesCorroborated,
		&i.RidesRejected,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getTripSummary = `-- name: GetTripSummary :one
SELECT t.id, t.vehicle_id, v.label AS vehicle_label, t.user_id, u.name AS driver_name,
       t.route_id, t.gtfs_trip_id, t.start_time, t.end_time, t.status
FROM trips t
JOIN users u ON u.id = t.user_id
JOIN vehicles v ON v.id = t.vehicle_id
WHERE t.id = $1
`

type GetTripSummaryRow struct {
	ID           int64
	VehicleID    string
	VehicleLabel string
	UserID       int64
	DriverName   string
	RouteID      string
	GtfsTripID   string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Status       string
}

func (q *Queries) GetTripSummary(ctx context.Context, id int64) (GetTripSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTripSummary, id)
	var i GetTripSummaryRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.VehicleLabel,
		&i.UserID,
		&i.DriverName,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, role, active, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, label, agency_tag, active, created_at, updated_at
FROM vehicles
WHERE id = $1
`

type GetVehicleByIDRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetVehicleByID(ctx context.Context, id string) (GetVehicleByIDRow, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i GetVehicleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AgencyTag,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocationPoint = `-- name: InsertLocationPoint :exec
INSERT INTO location_points (vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLocationPointParams struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) InsertLocationPoint(ctx context.Context, arg InsertLocationPointParams) error {
	_, err := q.db.Exec(ctx, insertLocationPoint,
		arg.VehicleID,
		arg.TripID,
		arg.Latitude,
		arg.Longitude,
		arg.Bearing,
		arg.Speed,
		arg.Accuracy,
		arg.Timestamp,
		arg.DriverID,
	)
	return err
}

const insertRide = `-- name: InsertRide :one
INSERT INTO rides (id, rider_id, trip_id, start_date, route_id, vehicle_id, boarding_stop_id, destination_stop_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, rider_id, trip_id, start_date, route_id, vehicle_id, boarding_stop_id, destination_stop_id, status, state, corroborated, end_reason, points_total, points_matched, points_corroborated, points_contradicted, started_at, ended_at, updated_at
`

type InsertRideParams struct {
	ID                string
	RiderID           string
	TripID            string
	StartDate         string
	RouteID           string
	VehicleID         string
	BoardingStopID    string
	DestinationStopID string
}

func (q *Queries) InsertRide(ctx context.Context, arg InsertRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, insertRide,
		arg.ID,
		arg.RiderID,
		arg.TripID,
		arg.StartDate,
		arg.RouteID,
		arg.VehicleID,
		arg.BoardingStopID,
		arg.DestinationStopID,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.TripID,
		&i.StartDate,
		&i.RouteID,
		&i.VehicleID,
		&i.BoardingStopID,
		&i.DestinationStopID,
		&i.Status,
		&i.State,
		&i.Corroborated,
		&i.EndReason,
		&i.PointsTotal,
		&i.PointsMatched,
		&i.PointsCorroborated,
		&i.PointsContradicted,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTripsByVehicle = `-- name: ListActiveTripsByVehicle :many
SELECT DISTINCT ON (t.vehicle_id)
       t.vehicle_id, t.id, t.route_id, t.gtfs_trip_id, t.user_id, u.name AS driver_name
FROM trips t
JOIN users u ON u.id = t.user_id
WHERE t.status = 'active'
ORDER BY t.vehicle_id, t.start_time DESC
`

type ListActiveTripsByVehicleRow struct {
	VehicleID  string
	ID         int64
	RouteID    string
	GtfsTripID string
	UserID     int64
	DriverName string
}

// Schema guarantees one active trip per USER, not per vehicle; newest active
// trip per vehicle is the defined tiebreak (spec §4.8).
func (q *Queries) ListActiveTripsByVehicle(ctx context.Context) ([]ListActiveTripsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByVehicle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTripsByVehicleRow
	for rows.Next() {
		var i ListActiveTripsByVehicleRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.ID,
			&i.RouteID,
			&i.GtfsTripID,
			&i.UserID,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVehiclesByUser = `-- name: ListActiveVehiclesByUser :many
SELECT v.id, v.label, v.agency_tag, v.active, v.created_at, v.updated_at
FROM vehicles v
JOIN user_vehicles uv ON uv.vehicle_id = v.id
WHERE uv.user_id = $1 AND v.active = TRUE
ORDER BY v.label, v.id
LIMIT 1000
`

type ListActiveVehiclesByUserRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Driver-facing: active vehicles assigned to a user. LIMIT is a safety bound, not pagination.
func (q *Queries) ListActiveVehiclesByUser(ctx context.Context, userID int64) ([]ListActiveVehiclesByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveVehiclesByUserRow
	for rows.Next() {
		var i ListActiveVehiclesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AgencyTag,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRides = `-- name: ListRides :many
SELECT id, rider_id, trip_id, start_date, route_id, vehicle_id, boarding_stop_id, destination_stop_id, status, state, corroborated, end_reason, points_total, points_matched, points_corroborated, points_contradicted, started_at, ended_at, updated_at FROM rides WHERE status = $1 ORDER BY started_at DESC LIMIT $2 OFFSET $3
`

type ListRidesParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListRides(ctx context.Context, arg ListRidesParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRides, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.TripID,
			&i.StartDate,
			&i.RouteID,
			&i.VehicleID,
			&i.BoardingStopID,
			&i.DestinationStopID,
			&i.Status,
			&i.State,
			&i.Corroborated,
			&i.EndReason,
			&i.PointsTotal,
			&i.PointsMatched,
			&i.PointsCorroborated,
			&i.PointsContradicted,
			&i.StartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripLocations = `-- name: ListTripLocations :many
SELECT lp.latitude, lp.longitude, lp.bearing, lp.speed, lp.accuracy,
       lp.timestamp, lp.trip_id, lp.received_at
FROM location_points lp
JOIN trips t ON t.id = $1
WHERE lp.vehicle_id = t.vehicle_id
  AND lp.driver_id = t.user_id::text
  AND lp.received_at >= t.start_time
  AND lp.received_at <= COALESCE(t.end_time, NOW())
ORDER BY lp.received_at ASC
LIMIT 10000
`

type ListTripLocationsRow struct {
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	TripID     string
	ReceivedAt pgtype.Timestamptz
}

// Trail derivation per spec §4.5: location_points.trip_id is a client string,
// not trips.id, so trail points are matched by vehicle + driver + time window.
func (q *Queries) ListTripLocations(ctx context.Context, id int64) ([]ListTripLocationsRow, error) {
	rows, err := q.db.Query(ctx, listTripLocations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripLocationsRow
	for rows.Next() {
		var i ListTripLocationsRow
		if err := rows.Scan(
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.TripID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, active, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByVehicle = `-- name: ListUsersByVehicle :many
SELECT user_id, vehicle_id, created_at
FROM user_vehicles
WHERE vehicle_id = $1
ORDER BY created_at DESC
LIMIT 1000
`

// safety bound; not pagination
func (q *Queries) ListUsersByVehicle(ctx context.Context, vehicleID string) ([]UserVehicle, error) {
	rows, err := q.db.Query(ctx, listUsersByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserVehicle
	for rows.Next() {
		var i UserVehicle
		if err := rows.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, label, agency_tag, active, created_at, updated_at
FROM vehicles
ORDER BY created_at DESC
`

type ListVehiclesRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListVehicles(ctx context.Context) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AgencyTag,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByUser = `-- name: ListVehiclesByUser :many
SELECT user_id, vehicle_id, created_at
FROM user_vehicles
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1000
`

// safety bound; not pagination
func (q *Queries) ListVehiclesByUser(ctx context.Context, userID int64) ([]UserVehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserVehicle
	for rows.Next() {
		var i UserVehicle
		if err := rows.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRiderTier = `-- name: SetRiderTier :exec
UPDATE riders SET tier = $2 WHERE id = $1
`

type SetRiderTierParams struct {
	ID   string
	Tier string
}

func (q *Queries) SetRiderTier(ctx context.Context, arg SetRiderTierParams) error {
	_, err := q.db.Exec(ctx, setRiderTier, arg.ID, arg.Tier)
	return err
}

const setUserActive = `-- name: SetUserActive :execrows
UPDATE users SET active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID     int64
	Active bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVehicleActive = `-- name: SetVehicleActive :execrows
UPDATE vehicles SET active = $2, updated_at = NOW() WHERE id = $1
`

type SetVehicleActiveParams struct {
	ID     string
	Active bool
}

func (q *Queries) SetVehicleActive(ctx context.Context, arg SetVehicleActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVehicleActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startTrip = `-- name: StartTrip :one
INSERT INTO trips (user_id, vehicle_id, route_id, gtfs_trip_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, vehicle_id, route_id, gtfs_trip_id, start_time, end_time, status, created_at, updated_at
`

type StartTripParams struct {
	UserID     int64
	VehicleID  string
	RouteID    string
	GtfsTripID string
}

func (q *Queries) StartTrip(ctx context.Context, arg StartTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, startTrip,
		arg.UserID,
		arg.VehicleID,
		arg.RouteID,
		arg.GtfsTripID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchRider = `-- name: TouchRider :exec
UPDATE riders SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) TouchRider(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchRider, id)
	return err
}

const unassignUserVehicle = `-- name: UnassignUserVehicle :execrows
DELETE FROM user_vehicles
WHERE user_id = $1 AND vehicle_id = $2
`

type UnassignUserVehicleParams struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) UnassignUserVehicle(ctx context.Context, arg UnassignUserVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignUserVehicle, arg.UserID, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRideProgress = `-- name: UpdateRideProgress :exec
UPDATE rides SET state = $2, corroborated = $3, points_total = $4, points_matched = $5,
  points_corroborated = $6, points_contradicted = $7, updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

type UpdateRideProgressParams struct {
	ID                 string
	State              string
	Corroborated       bool
	PointsTotal        int32
	PointsMatched      int32
	PointsCorroborated int32
	PointsContradicted int32
}

func (q *Queries) UpdateRideProgress(ctx context.Context, arg UpdateRideProgressParams) error {
	_, err := q.db.Exec(ctx, updateRideProgress,
		arg.ID,
		arg.State,
		arg.Corroborated,
		arg.PointsTotal,
		arg.PointsMatched,
		arg.PointsCorroborated,
		arg.PointsContradicted,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, email = $2, role = $3
WHERE id = $4
RETURNING id, name, email, role, active, created_at, updated_at
`

type UpdateUserParams struct {
	Name  string
	Email string
	Role  string
	ID    int64
}

type UpdateUserRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// updated_at is maintained by the set_users_updated_at trigger.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicleInfo = `-- name: UpdateVehicleInfo :execrows
UPDATE vehicles SET label = $2, agency_tag = $3, updated_at = NOW() WHERE id = $1
`

type UpdateVehicleInfoParams struct {
	ID        string
	Label     string
	AgencyTag string
}

func (q *Queries) UpdateVehicleInfo(ctx context.Context, arg UpdateVehicleInfoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicleInfo, arg.ID, arg.Label, arg.AgencyTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdminVehicle = `-- name: UpsertAdminVehicle :one
INSERT INTO vehicles (id, label, agency_tag)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, agency_tag = EXCLUDED.agency_tag, active = true, updated_at = NOW()
RETURNING id, label, agency_tag, active, created_at, updated_at
`

type UpsertAdminVehicleParams struct {
	ID        string
	Label     string
	AgencyTag string
}

type UpsertAdminVehicleRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAdminVehicle(ctx context.Context, arg UpsertAdminVehicleParams) (UpsertAdminVehicleRow, error) {
	row := q.db.QueryRow(ctx, upsertAdminVehicle, arg.ID, arg.Label, arg.AgencyTag)
	var i UpsertAdminVehicleRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AgencyTag,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRider = `-- name: UpsertRider :one
INSERT INTO riders (id, installation_id, platform, app_id, app_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (installation_id) DO UPDATE
  SET last_seen_at = NOW(), app_version = EXCLUDED.app_version, platform = EXCLUDED.platform, app_id = EXCLUDED.app_id
RETURNING id, installation_id, platform, app_id, app_version, attested, score, tier, rides_total, rides_corroborated, rides_rejected, created_at, last_seen_at, (xmax = 0) AS created
`

type UpsertRiderParams struct {
	ID             string
	InstallationID string
	Platform       string
	AppID          string
	AppVersion     string
}

type UpsertRiderRow struct {
	ID                string
	InstallationID    string
	Platform          string
	AppID             string
	AppVersion        string
	Attested          bool
	Score             int32
	Tier              string
	RidesTotal        int32
	RidesCorroborated int32
	RidesRejected     int32
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	Created           bool
}

func (q *Queries) UpsertRider(ctx context.Context, arg UpsertRiderParams) (UpsertRiderRow, error) {
	row := q.db.QueryRow(ctx, upsertRider,
		arg.ID,
		arg.InstallationID,
		arg.Platform,
		arg.AppID,
		arg.AppVersion,
	)
	var i UpsertRiderRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Platform,
		&i.AppID,
		&i.AppVersion,
		&i.Attested,
		&i.Score,
		&i.Tier,
		&i.RidesTotal,
		&i.RidesCorroborated,
		&i.RidesRejected,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Created,
	)
	return i, err
}

const upsertVehicle = `-- name: UpsertVehicle :exec
INSERT INTO vehicles (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE SET updated_at = NOW()
`

func (q *Queries) UpsertVehicle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, upsertVehicle, id)
	return err
}

const vehicleExists = `-- name: VehicleExists :one
SELECT EXISTS(SELECT 1 FROM vehicles WHERE id = $1)
`

func (q *Queries) VehicleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, vehicleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
